### ISSUE TITLE
Error Responder

### ISSUE THREAD

**Issue by MarcoVigna17** [jarcoal/httpmock#12]
Hi all guys!

I'm using your httpmock in a project, and I found it very clear and useful. I like it, and I will use it also in the future on other projects. 

I'm using it to mock http.Client, and I need to mock an error responder.

There's a way to do in on the actual version? Or will be in future releases?

Cheers

**Comment by dlebech** [comment]
@MarcoVigna17 I'm assuming that you mean that you want an easy way to create a responder that creates and error rather than a response. Something like this:
`responder := NewErrorResponder(errors.New("my error"))`

If that's what you're looking for, it's being added in #25 :)

**Comment by MarcoVigna17** [comment]
Yes was that! 

Thanks! :)

**Comment by dlebech** [comment]
@MarcoVigna17 glad to hear it :smiley: I'll close this issue then.
