### ISSUE TITLE
[Question] How to add custom values in the response header ?

### ISSUE THREAD

**Issue by Sted-octo** [jarcoal/httpmock#131]
Hi,

I'd like to mock an API call that return the count of total lines in a value put in the response header.
The API has parameters to indicate the page et the number of expected result per page. The response contains the number of total result lines, so it's possible to know how many call to do with the right page number.

I'm looking for the best way to do it with this httpmock package.
Is that doable ?
what would be the best way to do it.
Best regards
Steeve

**Comment by maxatome** [comment]
Hello,
as a [`Responder`](https://pkg.go.dev/github.com/jarcoal/httpmock#Responder) is a function you can do what you want inside it, as altering the `Header` field of the [`Response`](https://pkg.go.dev/net/http#Response) instance you return.

```go
httpmock.RegisterResponder("GET", "/foo",
  func(req *http.Request) (*http.Response, error) {
    ...
    resp, _ := httpmock.NewJsonResponse(200, body)
    resp.Header.Add("X-My-Header", "42")
    return resp, nil
  })
```

**Comment by Sted-octo** [comment]
Hi,

Thank you very much, It's working well.

Have a good day.
