### ISSUE TITLE
Capture the request body

### ISSUE THREAD

**Issue by ignacio83** [jarcoal/httpmock#135]
I think is not hard adds a Responder who capture the request body. I would like validate the request who arrive in http server. 
Something like that:

``` 
func NewCaptureResponder(captor *Captor, res *http.Response) func(req *http.Request) (*http.Response, error) {
	return func(req *http.Request) (*http.Response, error) {
		buf := bytes.Buffer{}
		_, err := io.Copy(&buf, req.Body)
		if err != nil {
			return nil, err
		}
		captor.Value = buf.String()
		return res, nil
	}
}
```

```
requestCaptor := Captor{}
responder := NewCaptureResponder(&requestCaptor, httpmock.NewStringResponse(tt.givenStatus, tt.givenResponse))
				httpmock.RegisterResponder(tt.givenMethod, tt.givenUrl, responder)
```

What you think about? Make sense? If you agree. I could submit a pull request with that.

**Comment by maxatome** [comment]
Hello thanks for your interest in httpmock.
Do you have a real use case of such feature? Do you want to test the body later?

I already encountered the case where I wanted to test the incoming JSON body, so using [go-testdeep](github.com/maxatome/go-testdeep) for example:
```go
httpmock.RegisterResponder(http.MethodPost, "/person",
	func(req *http.Request) (*http.Response, error) {
		td.Cmp(t, req.Body, td.Smuggle(json.RawMessage{}, td.JSON(`{"name":"John Doe","age":42}`)))
		return httpmock.NewStringResponse(201, `{"id":1234}`), nil
	})
```
([playground](https://go.dev/play/p/caX2Gq4IbfF))

but as you see it is very specific and changing from tests to tests.
IMHO it does not deserve a specific new function for that.

For your proposal, what happens if the responder is called multiple times? Should Captor handle multiple captures? It would complicates more than it will help, I think.

**Comment by ignacio83** [comment]
Hi @maxatome,

I think if responder is called multiple times, I have to store that in a Slice. 

I proposal that, because similar libraries have ways to match body:
- Nock: https://github.com/nock/nock#specifying-request-body
- Mockserver: https://www.mock-server.com/mock_server/getting_started.html#request_body_matchers

**Comment by maxatome** [comment]
Hello,
if I understand well your given examples, you don't want to capture the body but you want to add a layer to match the request body contents before mocking the call, right?

**Comment by ignacio83** [comment]
Yes, you are right.

Verify the request is an option for do that.

**Comment by maxatome** [comment]
Currently we only check method and URL.
If you want to check body (and also header) content, what API do you propose?

**Comment by ignacio83** [comment]
Hi @maxatome, I have two proposals:

1) Adds a function at package httpmock with a Matcher as type function.
```go
type Matcher func(*http.Request) error

func RegisterResponderAndMatcher(method, url string, responder Responder, matcher Matcher) {
	...
}
```

2) Adds function at package httpmock with a RouteMatcher as type struct who encapsulates URL and Method. It also has a a Matcher type as function.
```go
type RouteMatcher struct {
	Method string
	URL    string
        Matcher Matcher
}

type Matcher func(*http.Request) error

func RegisterResponderWithMatcher(rm RouteMatcher, responder Responder) {
	...
}
```

In both solutions we can provide built-in matchers like: ExactMatcher, ContainsMatcher, etc...

Of course in both solutions we have do add/modify internal code to add this behaviors.

**Comment by maxatome** [comment]
Hi @ignacio83,

3. no new function/method but 2 new types `CustomMatcher` & `CustomMatcherList` allowing to do:
   ```go
   cml := NewCustomeMatcherList(martcher1, matcher2, ...)
   httpmock.RegisterResponder("GET", "/foo", cml.Responder())
   ...
   cml.Append(matcher3) // no need to call RegisterResponder() again
   ...
   cml.Prepend(matcher4) // no need to call RegisterResponder() again
   ```
   https://go.dev/play/p/zM4PxiosuzK
   BUT in this case we have no stats ([GetCallCountInfo](https://pkg.go.dev/github.com/jarcoal/httpmock#MockTransport.GetCallCountInfo)) per matcher…

I like your 2. but quickly I have a few remarks:
- IMHO `Matcher` should be `func(*http.Request) bool`, as it is easier to return a bool than to build an error that will not be used;
- shouldn't a `RouteMatcher` have an optional `Name` field? to retrieve it in stats and to help the user when no responder are found (as we already do currently). By default it can be the "FILE:LINE" of the last `RegisterResponderWithMatcher` call;
- `RouteMatcher` should have at least 2 constructors:
  - `NewRouteMatcherRegexp(method string, urlRegexp *regexp.Regexp, matcher Matcher)` to mimic `RegisterRegexpResponder` behavior and so `Matcher` should embed a `rx *regexp.Regexp` private field,
  - `NewRouteMatcherWithQuery(method, path string, query any, matcher Matcher)` to mimic `RegisterResponderWithQuery` behavior.

What do you think?

I like the idea that we can combine with [go-testdeep](https://go-testdeep.zetta.rocks/):
```go
func JSONBodyMatcher(op td.TestDeep) Matcher {
  return func (req *http.Request) bool {
    return td.EqDeeply(req.Body, td.Smuggle(json.RawMessage{}, op)
  }
}

// then, to only catch John creation:
httpmock.RegisterResponderWithMatcher(
  NewRouteMatcher("POST", "/person", JSONBodyMatcher(td.SuperJSONOf(`{"name":"John"}`))),
  responder,
)
// or using JSONPointer operator:
httpmock.RegisterResponderWithMatcher(
  NewRouteMatcher("POST", "/person", JSONBodyMatcher(td.JSONPointer("/name", "John"))),
  responder,
)
```

**Comment by ignacio83** [comment]
Hi @maxatome,

I didn't know the de testdeep and now I realize that the httpmock already depends of that.

I agree with your comments.

What do you think? In the next week I have some time to code and submit a pull request. Or do you prefer code it by yoursef?

**Comment by maxatome** [comment]
Hi @ignacio83,

httpmock only depends on go-testdeep for its tests, so it is not a runtime dependency and it should stay as is. But I could provide a new external tdhttpmock repo containing some helpers.

I just created the [matchers](https://github.com/jarcoal/httpmock/tree/matchers) branch with all the branching logic, so the hard work is done and mostly tested. The new `Register*Responder` functions/methods are missing as I am not sure what is the best way to provide it to the user.

Either duplicate existing functions/methods and add a `matcher Matcher` param:
```go
func (m *MockTransport) RegisterMatcherResponder(method, url string, matcher Matcher, responder Responder)
func (m *MockTransport) RegisterRegexpMatcherResponder(method string, urlRegexp *regexp.Regexp, matcher Matcher, responder Responder)
func (m *MockTransport) RegisterMatcherResponderWithQuery(method, path string, query any, matcher Matcher, responder Responder)
```
or create a new `RouteMatcher` type, as we discussed in a previous comment, and provide:
```go
func (m *MockTransport) RegisterMatcherResponder(rm RouteMatcher, responder Responder)
```
plus many constructors to cover all existing cases (simple, regexp & query):
```go
type RouteMatcher struct {
	method  string
	url     string
	rx      *regexp.Regexp
	matcher Matcher
}

func NewRouteMatcher(method, url string, matcher Matcher) RouteMatcher
func NewRouteMatcherWithQuery(method, url string, query any, matcher Matcher) RouteMatcher
func NewRegexpRouteMatcher(method string, urlRegexp *regexp.Regexp, matcher Matcher) RouteMatcher
```

The new type seems interesting, but in the end it is more verbose and probably not the best choice. We have to think about the possibilities.

I let you test on your side as I won't be able to work on it until the middle of the week.

**Comment by maxatome** [comment]
Hi @ignacio83,

httpmock only depends on go-testdeep for its tests, so it is not a runtime dependency and it should stay as is. But I could provide a new external tdhttpmock repo containing some helpers.

I just created the [matchers](https://github.com/jarcoal/httpmock/tree/matchers) branch with all the branching logic, so the hard work is done and mostly tested. The new `Register*Responder` functions/methods are missing as I am not sure what is the best way to provide it to the user.

Either duplicate existing functions/methods and add a `matcher Matcher` param:
```go
func (m *MockTransport) RegisterMatcherResponder(method, url string, matcher Matcher, responder Responder)
func (m *MockTransport) RegisterRegexpMatcherResponder(method string, urlRegexp *regexp.Regexp, matcher Matcher, responder Responder)
func (m *MockTransport) RegisterMatcherResponderWithQuery(method, path string, query any, matcher Matcher, responder Responder)
```
or create a new `RouteMatcher` type, as we discussed in a previous comment, and provide:
```go
func (m *MockTransport) RegisterMatcherResponder(rm RouteMatcher, responder Responder)
```
plus many constructors to cover all existing cases (simple, regexp & query):
```go
type RouteMatcher struct {
	method  string
	url     string
	rx      *regexp.Regexp
	matcher Matcher
}

func NewRouteMatcher(method, url string, matcher Matcher) RouteMatcher
func NewRouteMatcherWithQuery(method, url string, query any, matcher Matcher) RouteMatcher
func NewRegexpRouteMatcher(method string, urlRegexp *regexp.Regexp, matcher Matcher) RouteMatcher
```

The new type seems interesting, but in the end it is more verbose and probably not the best choice. We have to think about the possibilities.

I let you test on your side as I won't be able to work on it until the middle of the week.

**Comment by maxatome** [comment]
#79 related.

**Comment by maxatome** [comment]
I forgot to mention that a Matcher must have a name, except the default one (= nil matcher func). So the Matcher type should either be a struct, not a function as in the branch, or a name should be passed as well as the Matcher itself in functions accepting one.

**Comment by maxatome** [comment]
I just fixed `Matcher` type in [matchers](https://github.com/jarcoal/httpmock/tree/matchers) branch:
```go
// MatcherFunc type is the function to use to check a Matcher matches
// an incoming request.
type MatcherFunc func(req *http.Request) bool

// Matcher type defines a match case. The zero Matcher{} corresponds
// to the default case. Otherwise, Name and Matcher can never have the
// zero value.
type Matcher struct {
	Name  string
	Match MatcherFunc // can be nil → means always true, in this case Name == ""
}
```

**Comment by maxatome** [comment]
@ignacio83 I created a PR as I just added all Register Matcher methods/functions.

Example of use in [TestRegisterMatcherResponder test](https://github.com/jarcoal/httpmock/pull/136/files#diff-89ae70865ace384239355ee0c882acef79b281a7c88c53c22058d75941cd2643R97).

Remaining things to do:
- full test coverage
- documentation

**Comment by ignacio83** [comment]
Thank you

**Comment by maxatome** [comment]
#136 merged, so this issue is resolved.
Thanks for your help @ignacio83!

**Comment by glebsts** [comment]
@maxatome Hello, sorry for bothering, but do you plan to make some minor release for that? readme on ~master~ default branch promises `MatcherResponder` but latest release is from May 6 and doesn't have it.

**Comment by maxatome** [comment]
Hi @glebsts, I will try to do it before 2023. Stay tuned. :)
Note you can use this feature before the release:
```
go get github.com/jarcoal/httpmock@b9e83a2

**Comment by glebsts** [comment]
guess it didn't happen :(

**Comment by maxatome** [comment]
You guess well :(
Before the end of the week, I promise. Sorry.

**Comment by maxatome** [comment]
Done @glebsts, and sorry for the delay.
