### ISSUE TITLE
Watchout for custom implementation of http.Transport!

### ISSUE THREAD

**Issue by rue-vmom** [jarcoal/httpmock#22]
If your package implements your own http.Transport (for example, to bypass tls cert verification), it will not allow httpmock to intercept requests as it depends on your http.Client using the default http.DefaultTransport.  Would be nice if this warning was in the readme.

**Comment by rossnoble** [comment]
Yeah man, I lost a lot of time with this one. Good find though. Will have to make time to make a PR for an improvement.

**Comment by dlebech** [comment]
@rue-vmom @rossnoble thanks for reporting this. Could you elaborate on what this issue is about. I don't entirely follow. It is possible to activate the mocks with a non-default client and transport using [`ActivateNonDefault`](https://github.com/jarcoal/httpmock/blob/6aa33143427f6eb0bebcc0af42e8db85e39a42c0/transport.go#L193-L202). Does this not work for your use case?

**Comment by rossnoble** [comment]
@dlebech: I was trying to mock https://github.com/SparkPost/gosparkpost (which uses a custom http transport), but it wasn't intercepting the requests out of the box like with other libs. I got it working by passing a default http client to the sparkpost config, but I wouldn't have thought to do that had @rue-vmom not mentioned something. I didn't notice `ActivateNonDefault()` at the time, which is probably the better solution.

I think the suggestion is to either have a warning in the code, or even just a note in the README.

**Comment by malnick** [comment]
I ran into this to, `ActivateNonDefault(my.client)` worked for me. Would a PR that adds an example to the root README.md be accepted? Documenting this higher up without having to go through the code might safe some people a bit of pain.

**Comment by dlebech** [comment]
@malnick that would be very nice thank you :-) If you could open a PR for both the `master` and `v1` branch you will get bonus Internet points 😃
