### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by dlebech** [jarcoal/httpmock#23]
It looks like this project is not getting any attention lately. Since it's still number one result on Google for http mocking in golang (at least for me), I feel it would be a shame if it dies.

To anyone else that read this issue: I have tried to reach out directly to Jared to see if we can revive this project and take a look at the current open PRs. I will be happy to help with bringing this project forward if necessary.

On a different note, the library works for me as-is, and I don't necessarily feel like it has to grow to huge proportions. But at least some faster responsiveness on issues and pull requests would be greatly appreciated, and I hope that the community would agree with me on this.

Cheers :-)

**Comment by jarcoal** [comment]
Yeah I apologize, but this project has fallen off my radar.  I'm not writing much Go anymore, so haven't had a need for it.

At one point @SchumacherFM offered to take over and I invited him as a collab but it looks like he never accepted.

If you or anyone else would like to collab, please let me know and I will invite.

**Comment by dlebech** [comment]
@jarcoal no worries, I'm happy that you got back to me so quick. Yes, I would like to help out if you'll let me 😃 

What I would initially just do is take a look at the PRs and open issues to give some responses to the other contributors. I have used this lib in three different projects now and the simplicity has suited most situations so I don't think there's a great need to build big new features. Either way, I would be happy to step in and help out. Let me know what you think.

**Comment by jarcoal** [comment]
Cool, I just made you a collaborator.

I didn't really have any major rules in place for accepting PRs, but it was my goal for the project to not introduce any external dependencies; I'm not sure if that still makes sense.

**Comment by dlebech** [comment]
Awesome thanks. I think it totally makes sense to not bloat the library. Just keep it simple, easy to use and without other dependencies 👍

**Comment by dlebech** [comment]
I'll close this issue for now and take a look at the PRs and issues over the weekend.
