### ISSUE TITLE
NewGZipResponder

### ISSUE THREAD

**Issue by willis7** [jarcoal/httpmock#27]
Some API's return GZip compressed responses. This would be a really useful feature to support.

**Comment by dlebech** [comment]
Thanks for the suggestion. I'll look into how easy/feasible this is once I have a bit of time leftover :)

**Comment by maxatome** [comment]
@willis7 I don't know if you still need the feature, but what do you need exactly?
Is it to only set the request `Accept-Encoding` header to `gzip` and let your client gunzip the body content?
If yes, that is pretty simple to implement as we can mimic the net/http.Transport behavior.
Tell us.

**Comment by willis7** [comment]
Hi @maxatome, I have not use httpmock in a while. I will close this issue for completeness.
