### ISSUE TITLE
Default responder

### ISSUE THREAD

**Issue by PumpkinSeed** [jarcoal/httpmock#32]
Can I somehow create a default responder, which is handle all other incoming request? 

The problem: 
If I'm register a responder for a specific endpoint and if it has been changed in the code I get an panic usually, because if there isn't responder, so the http.Response will be empty. 

Possible solution:
Create a function or something like that as the following:

```
httpmock.DefultResponder(
	func(req *http.Request) (*http.Response, error) {
		// do something
		return httpmock.NewStringResponse(500, ""), nil
	},
)
```

**Comment by dlebech** [comment]
@PumpkinSeed When httpmock fails to find a responder for an endpoint, it falls back to the [`ConnectionFailure` responder](https://godoc.org/gopkg.in/jarcoal/httpmock.v1#ConnectionFailure)

You can register your own fallback responder with [`RegisterNoResponder`](https://godoc.org/gopkg.in/jarcoal/httpmock.v1#RegisterNoResponder), e.g.:
`httpmock.RegisterNoResponder(httpmock.NewStringResponder(500, ""))`

I hope this helps.

**Comment by PumpkinSeed** [comment]
This is exactly what I looked for, just didn't find it. Thanks
