### ISSUE TITLE
Allow some http request

### ISSUE THREAD

**Issue by andrysds** [jarcoal/httpmock#33]
As far I know, httpmock.Activate() will block all http request that go out from the project.
Can you make a method for allowing some http request?

**Comment by maxatome** [comment]
Without changing the code of httpmock, you have 2 possibilities:
1. you can forward the call in your mocked calls;
1. you can use a different client for the calls you don't want to mock. 

Otherwise, you can submit a PR to allow this :)

**Comment by sarahyablok** [comment]
https://github.com/jarcoal/httpmock/blob/v1/transport.go#L527-L533

**Comment by maxatome** [comment]
@sarahyablok you are completely right! I missed this solution... Well done.

**Comment by eloo** [comment]
for the record:
The code mentioned from @sarahyablok can be found here
https://github.com/jarcoal/httpmock/blob/df0bb7804128c6d1255e14e496fd04e93b6a6c55/transport.go#L527-L533

the whole solution could look like this
```
	httpmock.RegisterNoResponder(httpmock.InitialTransport.RoundTrip)
```

**Comment by MangelMaxime** [comment]
Took me way to long to find this issue and solution.

Thank you for @eloo for the permalink
