### ISSUE TITLE
Query param encoding issue

### ISSUE THREAD

**Issue by rgalanakis** [jarcoal/httpmock#56]
There remains in #54 an issue with encoding of query parameters. Easy to repro by adding `testUrlPath + "?a=b%3Dc"` as a test url in `TestRegisterResponderWithQuery`. When using RegisterResponderWithQuery, the responder URL uses an unescaped query string (`a=b=c`), whereas the http request uses the original escaped query string.

I believe that #55 would fix this but haven't tried. I would submit a fix but I believe #55 is a better way to go.

**Comment by rgalanakis** [comment]
Just confirming that #55 fixes this issue and seems to work great.

**Comment by google-bigqueryneural** [comment]
> Just confirming that [#55](https://github.com/jarcoal/httpmock/pull/55) fixes this issue and seems to work great.





https://black-hairedarbitrary-pr.github.io/WyHtwuSmOgNPaFb8w_NCzvJa7hhJZKUkSklkY0Q/
