### ISSUE TITLE
Query paramter with no value

### ISSUE THREAD

**Issue by itchyny** [jarcoal/httpmock#66]
Recent change #50 in the v1 branch breaks the behavior of query parameter without values. Query parameter with no value is valid due to RFC 3986.
Here's a patch to test the case.
```diff
--- a/transport_test.go
+++ b/transport_test.go
@@ -217,6 +217,9 @@ func TestMockTransportPathOnlyFallback(t *testing.T) {
 		"/hello/world?query=string&query=string2": {
 			testUrl + "hello/world?query=string&query=string2",
 		},
+		"/hello/world?query": {
+			testUrl + "hello/world?query",
+		},
 		"/hello/world#fragment": {
 			testUrl + "hello/world#fragment",
 		},
```
Ping to the related patch authors: @konalegi (for #50), @Zanadar (for #55) and @maxatome (for #61)

**Comment by maxatome** [comment]
@itchyny could you check with last commit of #61 ?

**Comment by itchyny** [comment]
It looks like it passes the test case in my comment, thanks. But I'm afraid looking up `?q` against mock `?q=` succeeds but `?q=` against `?q` fails and users are confused by this asymmetric behavior. I'm not sure how useful the strict order of RegisterResponder is. Normalizing in RegisterResponder is the another solution (in #55) (and honestly, I do prefer this way). This looks like a matter of library design.

**Comment by itchyny** [comment]
It looks like it passes the test case in my comment, thanks. But I'm afraid looking up `?q` against mock `?q=` succeeds but `?q=` against `?q` fails and users are confused by this asymmetric behavior. I'm not sure how useful the strict order of RegisterResponder is. Normalizing in RegisterResponder is the another solution (in #55) (and honestly, I do prefer this way) and, this will avoid the asymmetry. This looks like a matter of library design.

**Comment by maxatome** [comment]
Normalizing in `RegisterResponder` does not allow to register for a specific order of query parameters. That is why I prefer to first try to match with untouched query params given to `RegisterResponder`, then to falling back to sorted query params.
I do not have an easy solution to handle any-ordered query params given as a string with the current logic of storing responders, except ordering by yourself the url given to `RegisterResponder` or using `RegisterResponderWithQuery` or `RegisterResponderWithQueryValues` of course.
For information, I prepare an other PR introducing regexps matches, in which I will try to address this case too.

**Comment by maxatome** [comment]
FYI #61 just merged.

**Comment by itchyny** [comment]
Thank you! I understand the difference of RegisterResponder and RegisterResponderWithQuery.
