### ISSUE TITLE
Unable to emulate the http mock server

### ISSUE THREAD

**Issue by Tochemey** [jarcoal/httpmock#77]
I followed the instructions given on the readme to setup a mock http server.
However when I run the test I always get host not found exception which is the result that my httpclient instead of connecting to the mock server is trying to connect to an actual server.

Please advice.

Great work by the way

**Comment by maxatome** [comment]
Hi,
Perhaps could you provide a code example of what is not working for you? Without that, it will be difficult to go further...

**Comment by Tochemey** [comment]
I am mocking a fake URL that does not exist and it seems that httpmock does not start the http server in the background. Maybe I don't understand how to use it.

**Comment by Tochemey** [comment]
This is the sample code:
```
	transport := httpclient.CreateDefaultSecuredTransport()
	client := httpclient.CreateDefaultHTTPClient(transport)

	httpmock.ActivateNonDefault(client)
```

```
httpmock.RegisterResponder("POST", "https://fake.com/login", func(req *http.Request) (*http.Response, error) {
		data := url.Values{}
		data.Add("client_id", "5CDj3FgTPJz5JC5H7TCK")
		data.Add("client_secret", "pH7B8y5QBvKwT9gdVm5K82HW")

		req.Header.Add("Content-Type", "application/x-www-form-urlencoded")
		req.Header.Add("Content-Length", strconv.Itoa(len(data.Encode())))

		resp, err := httpmock.NewJsonResponse(200, &LoginResponse{
			AccessToken: uuid.New().String(),
			TokenType:   "Bearer",
			ExpiresIn:   8400,
		})

		if err != nil {
			return httpmock.NewJsonResponse(400, &ErrorResponse{
				Message:          "failed",
				Errors:           nil,
				DocumentationURL: "http://fake.com",
			})
		}

		return resp, nil
	})

	response, err := suite.api.Login(suite.context)
	suite.Require().Nil(err)
	suite.Require().NotNil(response)
	suite.T().Logf("login response %v", response)
```
The suite.api.Login hits the fake.com/login but I got connection refused.

**Comment by Tochemey** [comment]
Do I need to start a local http server before I can use the library

**Comment by Tochemey** [comment]
I was able to fix the error thank you.

**Comment by jigetage** [comment]
> I was able to fix the error thank you.

Hi buddy, could you tell me how you solve this? thank you! I met the same question with you~
https://github.com/jarcoal/httpmock/issues/88 my question
