### ISSUE TITLE
Configuration request and response from JSON file

### ISSUE THREAD

**Issue by patsevanton** [jarcoal/httpmock#81]
Hello.
Can support import request and response from JSON file configuration?
For example:
```
{
    "request": {
        "method": "GET",
        "url": "/test"
    },
    "response": {
        "status": 200,
        "body": "test 200 OK\n"
    }
}
``` 

Examples run 
```
curl http://localhost/test
test 200 OK
```

**Comment by maxatome** [comment]
Hello, yes you can do it pretty easily.

If you ask for the integration of such feature in httpmock why not, but the format of the json file has to be more complete.
Typically, one should import one route yes, but several routes too for one json file.
Body request should be given too, and so its content-type.
Content-type is missing from the response too.
Do not forget the possibility to set headers in response.

**Comment by patsevanton** [comment]
Hello.

I search, search and find utility https://github.com/brianmoran/mockify
Thank you.
