### ISSUE TITLE
set response with string

### ISSUE THREAD

**Issue by syarifmhidayatullah** [jarcoal/httpmock#82]
why when I set response with string (exp: `ok`) it will return `"ok"` instead of `ok`

**Comment by maxatome** [comment]
coz you use [`NewJsonResponder()`](https://godoc.org/github.com/jarcoal/httpmock#NewJsonResponder) instead of [`NewStringResponder()`](https://godoc.org/github.com/jarcoal/httpmock#NewStringResponder)?

**Comment by syarifmhidayatullah** [comment]
yes, may bad, thank you
