### ISSUE TITLE
Use http status number with text code instead of just the status number as a string

### ISSUE THREAD

**Issue by amasare** [jarcoal/httpmock#83]
https://github.com/jarcoal/httpmock/blob/e598472b238f5d2a505e1316886da2171f86bfa4/response.go#L134

According to https://golang.org/src/net/http/response.go?s=731:4298#L25 the http Response object should return the http status number as well as the status text. So 

```
&http.Response{
		Status:        strconv.Itoa(status),
		StatusCode:    status,
		Body:          NewRespBodyFromString(body),
		Header:        http.Header{},
		ContentLength: -1,
	}
``` 

should be 

```&http.Response{
		Status:        strconv.Itoa(status) + " " + http.StatusText(status),
		StatusCode:    status,
		Body:          NewRespBodyFromString(body),
		Header:        http.Header{},
		ContentLength: -1,
	}
```

**Comment by maxatome** [comment]
If you want this feature to be really useful, please file a PR on v1 branch. master branch is deprecated now.

**Comment by constantoine** [comment]
Hi,

This was never fixed as it was never merged with v1. Would you be open for a small PR to be opened?

**Comment by maxatome** [comment]
Hi @constantoine, yes of course :)
