### ISSUE TITLE
Not able to mock request according to documentation

### ISSUE THREAD

**Issue by danthemanvsqz** [jarcoal/httpmock#92]
I posted my problem on SO
https://stackoverflow.com/questions/62434999/httpmock-is-not-intercepting-resty-call

**Comment by maxatome** [comment]
Cross-posting an issue on SO is a bit weird and not common.
Especially when the problem is rather simple: you don't mock the resty client you use in `ApiWrapper()`.

**Comment by danthemanvsqz** [comment]
@maxatome How would you go about mocking the client used in the function?
