### ISSUE TITLE
Race condition due to ResponderFromResponse() copying Body object

### ISSUE THREAD

**Issue by ascherkus** [jarcoal/httpmock#93]
I came across this when parallelizing some backend HTTP calls.

The short of it is that NewStringResponder(), NewBytesResponder(), etc... are all subject to racing since ResponderFromResponse() will create new http.Response objects use the same underlying Body object in each response.

My assumption would be that supplying a string in NewStringResponder() would be free of races. If so - I believe a possible fix is to inline ResponderFromResponse() into each method and ensure NewRespBodyFromString() or NewRespBodyFromBytes() is called for each new http.Response object created.

**Comment by maxatome** [comment]
Thanks for the report @ascherkus 
could you check the PR #94 please?

**Comment by ascherkus** [comment]
tested locally and works for me!

**Comment by maxatome** [comment]
Fine, [v1.0.6](https://github.com/jarcoal/httpmock/releases/tag/v1.0.6) released. Thanks for your help.
