### ISSUE TITLE
Implemented test case with mock. but it's not working

### ISSUE THREAD

**Issue by vinod023** [jarcoal/httpmock#99]
I implemented a code to get data from the API. And also wrote the test case with mock to that method by using [https://github.com/jarcoal/httpmock](https://github.com/jarcoal/httpmock). But mocking was not executing. Getting original data from the data. not getting mock data. tried in all the ways. but not working. can anyone help me please?
```go
func MakeAPIRequest(url string) ([]byte, error) {
    req, err := http.NewRequest(http.MethodGet, url, nil)
    if err != nil {
        log.Fatal(err)
    }
    tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }
    httpClient := &http.Client{Transport: tr}
    response, err := httpClient.Do(req)
    if err != nil {
        log.Fatal(err)
    }
    defer response.Body.Close()
    body, err := ioutil.ReadAll(response.Body)
    if err != nil {
        log.Fatal(err)
    }
    return body, nil
}
```

Test case code Is
```go
func TestMakeAPIRequest(t *testing.T) {
    httpmock.Activate()
    defer httpmock.DeactivateAndReset()
    httpmock.RegisterResponder("GET", "https://jsonplaceholder.typicode.com/users/1",
        httpmock.NewStringResponder(200, `{
            "id": 1,
            "name": "Leanne Graham Test Name",
            "username": "Bret",
            "email": "Sincere@april.biz",
            "address": {
              "street": "Kulas Light",
              "suite": "Apt. 556",
              "city": "Gwenborough",
              "zipcode": "92998-3874",
              "geo": {
                "lat": "-37.3159",
                "lng": "81.1496"
              }
            },
            "phone": "1-770-736-8031 x56442",
            "website": "hildegard.org",
            "company": {
              "name": "Romaguera-Crona",
              "catchPhrase": "Multi-layered client-server neural-net",
              "bs": "harness real-time e-markets"
            }
          }`))

    data, err := MakeAPIRequest("https://jsonplaceholder.typicode.com/users/1")
    fmt.Println("data:", string(data), err)
    fmt.Println(httpmock.GetCallCountInfo())
}
```

getting 0 when call
`fmt.Println(httpmock.GetCallCountInfo())` 

[https://stackoverflow.com/questions/64769575/implemented-test-case-with-mock-but-its-not-working](https://stackoverflow.com/questions/64769575/implemented-test-case-with-mock-but-its-not-working)

**Comment by maxatome** [comment]
Hello,
There is no magic. To be able to intercept the HTTP call, httpmock needs to replace the `http.Client.Transport`.
To achieve this, you have 3 solutions:
1. use `nil` as `Transport` in your client: this way `net/http` code uses `net/http.DefaultTransport` as default value, value just mocked by [`httpmock.Activate()`](https://godoc.org/github.com/jarcoal/httpmock#Activate);
1. put your transport in a global variable (with type `http.RoundTripper`) and override it in your test using [`httpmock.DefaultTransport`](https://godoc.org/github.com/jarcoal/httpmock#pkg-variables) or a specific [new mocked instance](https://godoc.org/github.com/jarcoal/httpmock#NewMockTransport);
1. put your client in a global variable and call [`httpmock.ActivateNonDefault()](https://godoc.org/github.com/jarcoal/httpmock#ActivateNonDefault) on it in your tests.

**Comment by vinod023** [comment]
Hi, Thanks for your reply. Can you give an example, please?

**Comment by maxatome** [comment]
```go
var Tr = &http.Transport{
    TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}

func MakeAPIRequest(url string) ([]byte, error) {
    req, err := http.NewRequest(http.MethodGet, url, nil)
    if err != nil {
        log.Fatal(err)
    }
    httpClient := &http.Client{Transport: Tr}
    response, err := httpClient.Do(req)
    if err != nil {
        log.Fatal(err)
    }
    defer response.Body.Close()
    body, err := ioutil.ReadAll(response.Body)
    if err != nil {
        log.Fatal(err)
    }
    return body, nil
}
```

and in your tests override global variable `Tr` value with `httpmock.DefaultTransport` before calling `MakeAPIRequest()`.

**Comment by vinod023** [comment]
I added DefaultTransport in test cases 
```go
func TestMakeAPIRequest(t *testing.T) {
	var tr = httpmock.DefaultTransport
	cl := &http.Client{Transport: tr}
	httpmock.ActivateNonDefault(cl)
	defer httpmock.DeactivateAndReset()
	httpmock.RegisterResponder("GET", "https://jsonplaceholder.typicode.com/users/1",
		httpmock.NewStringResponder(200, `{
			"id": 1,
			"name": "Leanne Graham Test Name",
			"username": "Bret",
			"email": "Sincere@april.biz",
			"address": {
			  "street": "Kulas Light",
			  "suite": "Apt. 556",
			  "city": "Gwenborough",
			  "zipcode": "92998-3874",
			  "geo": {
				"lat": "-37.3159",
				"lng": "81.1496"
			  }
			},
			"phone": "1-770-736-8031 x56442",
			"website": "hildegard.org",
			"company": {
			  "name": "Romaguera-Crona",
			  "catchPhrase": "Multi-layered client-server neural-net",
			  "bs": "harness real-time e-markets"
			}
		  }`))

	data, err := MakeAPIRequest("https://jsonplaceholder.typicode.com/users/1")
	fmt.Println("data:", string(data), err)
	fmt.Println(httpmock.GetCallCountInfo())

}
```

But no luck

`map[GET https://jsonplaceholder.typicode.com/users/1:0]`

httpmock was not working. getting original value

**Comment by maxatome** [comment]
If you don't follow what I said in my previous comment, it cannot work.

**Comment by vinod023** [comment]
> ```go
> var Tr = &http.Transport{
>     TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
> }
> 
> func MakeAPIRequest(url string) ([]byte, error) {
>     req, err := http.NewRequest(http.MethodGet, url, nil)
>     if err != nil {
>         log.Fatal(err)
>     }
>     httpClient := &http.Client{Transport: Tr}
>     response, err := httpClient.Do(req)
>     if err != nil {
>         log.Fatal(err)
>     }
>     defer response.Body.Close()
>     body, err := ioutil.ReadAll(response.Body)
>     if err != nil {
>         log.Fatal(err)
>     }
>     return body, nil
> }
> ```
> 
> and in your tests override global variable `Tr` value with `httpmock.DefaultTransport` before calling `MakeAPIRequest()`.

Hi @maxatome I implemented My business logic like this. But, when Can this from test cases, same original output I am getting. Mocking not working

**Comment by vinod023** [comment]
Here is my code:
```
var Tr = &http.Transport{
	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}

func MakeAPIRequest(url string) ([]byte, error) {
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		log.Fatal(err)
	}
	httpClient := &http.Client{Transport: Tr}
	response, err := httpClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer response.Body.Close()
	body, err := ioutil.ReadAll(response.Body)
	if err != nil {
		log.Fatal(err)
	}
	return body, nil
}
```


And it's test case code is:

```
func TestMakeAPIRequest(t *testing.T) {
	var tr = httpmock.DefaultTransport
	cl := &http.Client{Transport: tr}
	httpmock.ActivateNonDefault(cl)
	defer httpmock.DeactivateAndReset()
	httpmock.RegisterResponder("GET", "https://jsonplaceholder.typicode.com/users/1",
		httpmock.NewStringResponder(200, `{
			"id": 1,
			"name": "Leanne Graham Test Name",
			"username": "Bret",
			"email": "Sincere@april.biz",
			"address": {
			  "street": "Kulas Light",
			  "suite": "Apt. 556",
			  "city": "Gwenborough",
			  "zipcode": "92998-3874",
			  "geo": {
				"lat": "-37.3159",
				"lng": "81.1496"
			  }
			},
			"phone": "1-770-736-8031 x56442",
			"website": "hildegard.org",
			"company": {
			  "name": "Romaguera-Crona",
			  "catchPhrase": "Multi-layered client-server neural-net",
			  "bs": "harness real-time e-markets"
			}
		  }`))

	data, err := MakeAPIRequest("https://jsonplaceholder.typicode.com/users/1")
	fmt.Println("data:", string(data), err)
	fmt.Println(httpmock.GetCallCountInfo())

}
```
here mocking not workring

**Comment by maxatome** [comment]
Enclose your code section with triple backquotes otherwise it is very hard to read and I have to edit your message to add them.

You don't do what I suggest you. Your `cl` instance is never used to make any call, how would you want it works?

```
func TestMakeAPIRequest(t *testing.T) {
	httpmock.Activate()
	defer httpmock.DeactivateAndReset()

	saveTr := Tr
	defer func() { Tr = saveTr }()
	Tr = httpmock.DefaultTransport

	httpmock.RegisterResponder("GET", "https://jsonplaceholder.typicode.com/users/1",
		httpmock.NewStringResponder(200, `{
			"id": 1,
			"name": "Leanne Graham Test Name",
			"username": "Bret",
			"email": "Sincere@april.biz",
			"address": {
			  "street": "Kulas Light",
			  "suite": "Apt. 556",
			  "city": "Gwenborough",
			  "zipcode": "92998-3874",
			  "geo": {
				"lat": "-37.3159",
				"lng": "81.1496"
			  }
			},
			"phone": "1-770-736-8031 x56442",
			"website": "hildegard.org",
			"company": {
			  "name": "Romaguera-Crona",
			  "catchPhrase": "Multi-layered client-server neural-net",
			  "bs": "harness real-time e-markets"
			}
		  }`))

	data, err := MakeAPIRequest("https://jsonplaceholder.typicode.com/users/1")
	fmt.Println("data:", string(data), err)
	fmt.Println(httpmock.GetCallCountInfo())
}
```

**Comment by vinod023** [comment]
> Enclose your code section with triple backquotes otherwise it is very hard to read and I have to edit your message to add them.
> 
> You don't do what I suggest you. Your `cl` instance is never used to make any call, how would you want it works?
> 
> ```
> func TestMakeAPIRequest(t *testing.T) {
> 	httpmock.Activate()
> 	defer httpmock.DeactivateAndReset()
> 
> 	saveTr := Tr
> 	defer func() { Tr = saveTr }()
> 	Tr = httpmock.DefaultTransport
> 
> 	httpmock.RegisterResponder("GET", "https://jsonplaceholder.typicode.com/users/1",
> 		httpmock.NewStringResponder(200, `{
> 			"id": 1,
> 			"name": "Leanne Graham Test Name",
> 			"username": "Bret",
> 			"email": "Sincere@april.biz",
> 			"address": {
> 			  "street": "Kulas Light",
> 			  "suite": "Apt. 556",
> 			  "city": "Gwenborough",
> 			  "zipcode": "92998-3874",
> 			  "geo": {
> 				"lat": "-37.3159",
> 				"lng": "81.1496"
> 			  }
> 			},
> 			"phone": "1-770-736-8031 x56442",
> 			"website": "hildegard.org",
> 			"company": {
> 			  "name": "Romaguera-Crona",
> 			  "catchPhrase": "Multi-layered client-server neural-net",
> 			  "bs": "harness real-time e-markets"
> 			}
> 		  }`))
> 
> 	data, err := MakeAPIRequest("https://jsonplaceholder.typicode.com/users/1")
> 	fmt.Println("data:", string(data), err)
> 	fmt.Println(httpmock.GetCallCountInfo())
> }
> ```

Hi, Thanks for the reply. Tried the above one. getting type cast error. 
`cannot use httpmock.DefaultTransport (type *httpmock.MockTransport) as type *http.Transport in assignment`

**Comment by maxatome** [comment]
Fix the type of your global variable `Tr` and it is OK. I suggest you to read some docs:
- https://golang.org/ref/spec
- https://golang.org/pkg/net/http/

Hint: check the type of `Client.Transport` field https://golang.org/pkg/net/http/#Client

**Comment by vinod023** [comment]
I tried but, no luck. If you don't mind, can you suggest me the right one please?

**Comment by maxatome** [comment]
```go
var Tr http.RoundTripper = &http.Transport{
	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}
```

**Comment by vinod023** [comment]
I tried like this

```
var Tr http.RoundTripper = &http.Transport{
	TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
}

func MakeAPIRequest(url string) ([]byte, error) {
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		log.Fatal(err)
	}
	httpClient := &http.Client{Transport: Tr}
	response, err := httpClient.Do(req)
	if err != nil {
		log.Fatal(err)
	}
	defer response.Body.Close()
	body, err := ioutil.ReadAll(response.Body)
	if err != nil {
		log.Fatal(err)
	}
	return body, nil
}
```

Test case are

```
func TestMakeAPIRequest(t *testing.T) {
	httpmock.Activate()
	defer httpmock.DeactivateAndReset()

	saveTr := Tr
	defer func() { Tr = saveTr }()
	httpmock.RegisterResponder("GET", "https://jsonplaceholder.typicode.com/users/1",
		httpmock.NewStringResponder(200, `{
			"id": 1,
			"name": "Leanne Graham Test Name",
			"username": "Bret",
			"email": "Sincere@april.biz",
			"address": {
			  "street": "Kulas Light",
			  "suite": "Apt. 556",
			  "city": "Gwenborough",
			  "zipcode": "92998-3874",
			  "geo": {
				"lat": "-37.3159",
				"lng": "81.1496"
			  }
			},
			"phone": "1-770-736-8031 x56442",
			"website": "hildegard.org",
			"company": {
			  "name": "Romaguera-Crona",
			  "catchPhrase": "Multi-layered client-server neural-net",
			  "bs": "harness real-time e-markets"
			}
		  }`))

	data, err := MakeAPIRequest("https://jsonplaceholder.typicode.com/users/1")
	fmt.Println("data:", string(data), err)
	fmt.Println(httpmock.GetCallCountInfo())
}

```

But no luck. mock is not working

**Comment by maxatome** [comment]
Please read carefully my proposal https://github.com/jarcoal/httpmock/issues/99#issuecomment-732237119 and do not forget lines when you copy/paste.

**Comment by vinod023** [comment]
Hi @maxatome , Thanks for your help. Your comments helped me a lot.
